io-services:
  reader:
    class: org.jlab.jnp.grapes.io.HipoFrameReader
    name: HipoFrameReader
  writer:
    class: org.jlab.jnp.grapes.io.HipoFrameWriter
    name: HipoFrameWriter
services:
  - class: org.jlab.jnp.grapes.services.RandomWagon
    name: QA
configuration:
  custom-names:
    1: QA
  services:
    QA:
      id: 1
      prescale: 20.0 # prescale factor: randomly select `1/prescale` events
mime-types:
  - binary/data-hipo-frame
