graph TD;
   cd0[cd QA]:::manual-->qaTree;
   qaTree{{../outdat.$dataset/qaTree.json}}:::data --> import[import.sh]:::qa;
    import --> parse[parseQAtree.groovy<br>called automatically]:::qa;
    import --> qaLoc{{qa/ -> qa.$dataset/<br>qa/qaTree.json<br>qa/qaTable.dat}}:::data;
    parse --> qaLoc;
    
    qaLoc --> inspect[manual inspection<br>- view qaTable.dat<br>- view online monitor]:::manual;
    inspect --> edit{edit?};
    
    edit -->|yes|modify[modify.sh]:::qa;
    modify --> qaLoc;
    modify --> qaBak{{qa.$dataset/qaTree.json.*.bak}}:::data;
    qaBak --> undo[if needed, revert<br>modification with<br>undo.sh]:::qa;
    
    edit -->|no|cd[cd ..]:::qa;
    cd --> qa[exeQAtimelines.sh]:::qa;
    qaLoc --> qa;
    qa --> qaTL{{outmon.$dataset.qa/$timeline.hipo}}:::timeline;
    qa -->|updates|qaTree;
    qaTL --> deploy[deployTimelines.sh]:::qa
    deploy --> release[releaseTimelines.sh]:::qa
    qaTree --> release
    
    classDef data fill:#ff8;
    classDef manual fill:#fbb;
    classDef timeline fill:#8af;
    classDef qa fill:#f8f;
